[package]
name = "mechanix-shell"
description = "Touch optimized GUI shell for handheld devices running on wayland compositors"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[workspace]
members = [
    "app-drawer",
    "greeter",
    "home-screen",
    "keyboard",
    "lock-screen",
    "polkit-agent",
    "rotate-daemon",
    "settings-panel",
    "status-bar",
    "wallpaper-daemon",
    "commons/*",
    "app-switcher",
    "power-options",
]

[[bin]]
name = "mechanix-wallpaper-daemon"
path = "wallpaper-daemon/src/main.rs"

[workspace.package]
version = "0.1.0"
authors = ["Akshay Raina <akshayr@mechasystems.com>", "Shoaib Merchant <shoaibm@mechasystems.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/mecha-org/mechanix-gui"
homepage = "https://mecha.so"
categories = ["gui"]
keywords = ["linux", "shell", "mobile", "gui", "ui", "graphics", "interface", "widgets"]

[workspace.dependencies]
mctk_core = { git = "ssh://git@github.com/mecha-org/mctk.git", rev = "ff7eac0a9e1d6af8eda3d7554095293bc0379010" }
mctk_smithay = { git = "ssh://git@github.com/mecha-org/mctk.git", rev = "ff7eac0a9e1d6af8eda3d7554095293bc0379010" }
mctk_macros = { git = "ssh://git@github.com/mecha-org/mctk.git", rev = "ff7eac0a9e1d6af8eda3d7554095293bc0379010" }
mechanix_system_dbus_client = { path = "../services/system/client/dbus" }
mechanix_desktop_dbus_client = { path = "../services/desktop/client/dbus" }
smithay-client-toolkit = "0.18.0"
image = { version = "0.24.9", features = ["png", "jpeg"] }
futures = "0.3.30"
wayland-protocols-async = "1.0.0"
chrono = "0.4.31"
command = { path = "../commons/command"}
desktop_entries = { path = "./commons/desktop_entries"}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
futures-util = "0.3.30"
echo_client = { path = "./commons/echo-client"}
mechanix_status_bar_components = { path = "./commons/status-bar"}
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
anyhow = "1.0.79"
tokio = { version = "1.33", features = ["full"] }
zbus = { version = "4.1.2", features = ["tokio"] }
logind = { path = "../commons/logind"}