[package]
name = "camera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mctk_core = { git="https://github.com/namana-mecha/mctk.git", rev="11859c378cd486381680534fba588b5247d14e8f" }
mctk_smithay = { git="https://github.com/namana-mecha/mctk.git", rev="11859c378cd486381680534fba588b5247d14e8f" }
mctk_macros = { git="https://github.com/namana-mecha/mctk.git", rev="11859c378cd486381680534fba588b5247d14e8f" }
mctk_camera = { git="https://github.com/namana-mecha/mctk.git", rev="11859c378cd486381680534fba588b5247d14e8f" }
anyhow = { version = "1.0.75", features = ["backtrace"]}
gstreamer = "0.23.2"
gstreamer-app = "0.23.2"
gstreamer-video = "0.23.2"
image = { version = "0.24.9", features = ["jpeg"] }
jpeg-decoder = "0.3.0"
lazy_static = "1.5.0"
rand = "0.8.5"
regex = "1.7"
smithay-client-toolkit = "0.18.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"]}
thiserror = "1.0"
tokio = { version = "1.33", features = ["full"] }
rgb = "0.8.50"
