title: App Drawer  # Empty
app:
  id: app.drawer    # app-drawer
  text_multithreading: true   # false
  antialiasing: true    # false
  try_opengles_first: true    # false
window:
  size: [480, 440]  # [1024, 768]
  position: [0, 0]  # [0, 0]
  min_size: [480, 40]  # None
  max_size: null    # None
  visible: true   # true
  resizable: true   # true
  decorations: true   # true
  transparent: true    # false
  always_on_top: false    # false
  icon_path: null # Todo
css:
  default: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/css/style.css
layout:
  left: []
  center: []
  right: []
modules:
  apps:
    - app_id: chromium
      name: Chromium
      alias: chromium
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/chromium.png
    - app_id: mecha_connect
      name: Mecha Connect
      alias: mecha-connect
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/mecha_connect.png
    - app_id: test
      name: Kitty
      alias: kitty
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/kitty.png
    - app_id: chromium
      name: Chromium World Chromium World 
      alias: chromium
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/chromium.png
    - app_id: mecha_connect
      name: Mecha Connect
      alias: mecha-connect
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/mecha_connect.png
    - app_id: test
      name: Kitty
      alias: kitty
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/kitty.png
    - app_id: chromium
      name: Chromium
      alias: chromium
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/chromium.png
    - app_id: mecha_connect
      name: Mecha Connect
      alias: mecha-connect
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/mecha_connect.png
    - app_id: test
      name: Kitty
      alias: kitty
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/kitty.png
    - app_id: chromium
      name: Chromium
      alias: chromium
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/chromium.png
    - app_id: mecha_connect
      name: Mecha Connect
      alias: mecha-connect
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/mecha_connect.png
    - app_id: test
      name: Kitty
      alias: kitty
      icon: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/kitty.png
  search:
    icon:
      default: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/search.png    
  clear:
    icon:
      default: /home/parallels/Mecha/mecha-launcher/app_drawer/src/assets/pngs/clear.png    



