[package]
name = "mechanix-zbus-services"
description = "Zbus interface for Mechanix services"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[[bin]]
name = "mechanix-zbus-services"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
anyhow.workspace = true
zbus = { version = "4.1.2", features = ["tokio"] }
mechanix-bluetooth-ctl = { path = "../../ctl/bluetooth" }
mechanix-network-ctl = { path = "../../ctl/network" }
mechanix-power-ctl = { path = "../../ctl/power" }
mechanix-display-ctl = { path = "../../ctl/display" }
mechanix-host-metrics = { path = "../../ctl/host-metrics" }
serde_yaml = "0.9.25"
serde.workspace = true
zbus_polkit = { version = "4.0.0", features = ["tokio"] }
tracing.workspace = true

[features]
default = ["auth"]
auth = []


[package.metadata.deb]
name = "mechanix-zbus-server"
depends = "$auto"
assets = [
    # binary
    ["../../target/aarch64-unknown-linux-gnu/release/mechanix-zbus-server", "/usr/bin/", "755"],
    #dbus-conf
    ["./mecha-services-dbus.conf", "/etc/dbus-1/system.d/", "644"], 
    # settings
    ["./services-config-example.yml", "/etc/mechanix-gui/server/z-bus/", "644"],
   
]